In [1]:
import numpy as np

In [4]:
list(range(5))

[0, 1, 2, 3, 4]

In [5]:
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [6]:
#range function can only consider integers

In [8]:
np.arange(0.4,10.4,0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [11]:
list(np.arange(0.2,5.2,0.3))

[0.2,
 0.5,
 0.8,
 1.0999999999999999,
 1.4,
 1.7,
 1.9999999999999998,
 2.3000000000000003,
 2.6,
 2.9,
 3.2,
 3.5,
 3.8,
 4.1,
 4.4,
 4.7,
 5.0]

In [12]:
np.linspace(1,4,20)

array([1.        , 1.15789474, 1.31578947, 1.47368421, 1.63157895,
       1.78947368, 1.94736842, 2.10526316, 2.26315789, 2.42105263,
       2.57894737, 2.73684211, 2.89473684, 3.05263158, 3.21052632,
       3.36842105, 3.52631579, 3.68421053, 3.84210526, 4.        ])

In [16]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [21]:
np.zeros((2,3,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [22]:
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
arr = np.ones((3,4))

In [25]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [26]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [27]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
arr1 = np.eye(5)
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
import pandas as pd

In [45]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [47]:
np.random.rand(2,3)

array([[0.99350716, 0.69349788, 0.42111702],
       [0.43116863, 0.06420772, 0.43611309]])

In [48]:
np.random.randn(2,3)

array([[ 0.27186137,  1.12554967, -2.16643013],
       [-1.32369836, -0.43948403, -0.43391548]])

In [49]:
#randn mean = 0 and Standard deviation is 1 

In [50]:
np.random.randint(1,5,(3,4))

array([[4, 4, 1, 2],
       [4, 1, 1, 3],
       [4, 1, 3, 2]])

In [51]:
arr2 = np.random.randint(1,4,(3,4))

In [52]:
arr2

array([[2, 3, 3, 1],
       [3, 3, 2, 1],
       [3, 3, 1, 1]])

In [55]:
arr2.size

12

In [56]:
arr2.shape

(3, 4)

In [57]:
arr2.reshape(2,6)

array([[2, 3, 3, 1, 3, 3],
       [2, 1, 3, 3, 1, 1]])

In [58]:
arr2.reshape(2,-2)

array([[2, 3, 3, 1, 3, 3],
       [2, 1, 3, 3, 1, 1]])

In [59]:
arr2.reshape(4,3)

array([[2, 3, 3],
       [1, 3, 3],
       [2, 1, 3],
       [3, 1, 1]])

In [60]:
arr.reshape(4,-1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
arr2.reshape(4,-4343)

array([[2, 3, 3],
       [1, 3, 3],
       [2, 1, 3],
       [3, 1, 1]])

In [62]:
arr1 = np.random.randint(1,10,(5,6))

In [63]:
arr1

array([[8, 9, 7, 3, 3, 9],
       [8, 6, 6, 6, 5, 1],
       [5, 9, 1, 3, 2, 4],
       [3, 2, 2, 7, 4, 3],
       [7, 9, 1, 8, 8, 7]])

In [64]:
#filtering option

In [65]:
arr1 > 8

array([[False,  True, False, False, False,  True],
       [False, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True, False, False, False, False]])

In [67]:
arr1[arr1>8]

array([9, 9, 9, 9])

In [76]:
arr1[0,[0,1]]

array([8, 9])

In [84]:
arr1[[2,2:3],[2,2:4]]

SyntaxError: invalid syntax (2862036090.py, line 1)

In [87]:
arr1[2:4,[2,4]]

array([[1, 2],
       [2, 4]])

In [89]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [90]:
arr1+arr2

array([[4, 3, 4],
       [3, 3, 3],
       [3, 4, 3]])

In [91]:
arr1 

array([[2, 2, 2],
       [1, 1, 2],
       [1, 2, 1]])

In [92]:
arr2

array([[2, 1, 2],
       [2, 2, 1],
       [2, 2, 2]])

In [93]:
arr1@arr2

array([[12, 10, 10],
       [ 8,  7,  7],
       [ 8,  7,  6]])

In [94]:
#numpy broadcasting

In [96]:
arr = np.zeros((3,4))

In [97]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [99]:
a = np.array([1,2,3,4])

In [100]:
a

array([1, 2, 3, 4])

In [101]:
arr+1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [102]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])