In [1]:
import numpy as np

In [3]:
arr = np.array([2,3,4,335,6])

In [4]:
arr

array([  2,   3,   4, 335,   6])

In [8]:
np.sort(arr)

array([  2,   3,   4,   6, 335])

In [11]:
np.searchsorted(arr,5)

3

In [13]:
np.count_nonzero(arr)

5

In [15]:
np.extract(arr>5,arr)

array([335,   6])

In [16]:
#numpy - Byte  Swapping

In [17]:
arr.byteswap()

array([  33554432,   50331648,   67108864, 1325465600,  100663296])

In [18]:
arr

array([  2,   3,   4, 335,   6])

In [19]:
#numpy copy & views 

In [20]:
arr

array([  2,   3,   4, 335,   6])

In [21]:
a = np.copy(arr)

In [22]:
a

array([  2,   3,   4, 335,   6])

In [23]:
arr[0] = 100

In [24]:
a

array([  2,   3,   4, 335,   6])

In [25]:
arr

array([100,   3,   4, 335,   6])

In [26]:
a

array([  2,   3,   4, 335,   6])

In [27]:
b = arr.view()

In [28]:
b

array([100,   3,   4, 335,   6])

In [29]:
b[1] = 232

In [30]:
b

array([100, 232,   4, 335,   6])

In [31]:
arr

array([100, 232,   4, 335,   6])

In [32]:
#numpy - matrix library 

In [33]:
import numpy.matlib as nm

In [34]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [35]:
#matrix is a subclass of an array (in general or may be in numpy only) 

In [37]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [38]:
##numpy - linera algebra

In [45]:
arr1 = np.random.randint([[2,3],[4,5]])

In [46]:
arr1

array([[1, 1],
       [3, 3]])

In [48]:
arr2 = np.random.randint([[5,3],[4,5]])

In [49]:
arr2

array([[4, 0],
       [0, 4]])

In [50]:
np.dot(arr1,arr2)

array([[ 4,  4],
       [12, 12]])

In [51]:
arr1@arr2

array([[ 4,  4],
       [12, 12]])