In [1]:
import numpy as np

In [2]:
#numpy array manipulations

In [19]:
arr = np.random.randint(1,10,(4,4))

In [5]:
arr

array([[8, 8, 9, 5],
       [9, 4, 5, 7],
       [3, 3, 2, 9],
       [5, 2, 3, 4]])

In [6]:
arr.reshape(8,2)

array([[8, 8],
       [9, 5],
       [9, 4],
       [5, 7],
       [3, 3],
       [2, 9],
       [5, 2],
       [3, 4]])

In [7]:
arr.T

array([[8, 9, 3, 5],
       [8, 4, 3, 2],
       [9, 5, 2, 3],
       [5, 7, 9, 4]])

In [8]:
arr.flatten()

array([8, 8, 9, 5, 9, 4, 5, 7, 3, 3, 2, 9, 5, 2, 3, 4])

In [9]:
np.expand_dims(arr)

TypeError: expand_dims() missing 1 required positional argument: 'axis'

In [10]:
arr

array([[8, 8, 9, 5],
       [9, 4, 5, 7],
       [3, 3, 2, 9],
       [5, 2, 3, 4]])

In [13]:
arr = np.expand_dims(arr,axis = 1)

In [14]:
arr


array([[[8, 8, 9, 5]],

       [[9, 4, 5, 7]],

       [[3, 3, 2, 9]],

       [[5, 2, 3, 4]]])

In [18]:
np.expand_dims(arr,axis = 1)

array([[[[8, 8, 9, 5]]],


       [[[9, 4, 5, 7]]],


       [[[3, 3, 2, 9]]],


       [[[5, 2, 3, 4]]]])

In [25]:
arr= np.squeeze(arr)

In [26]:
np.squeeze(arr)

array([[5, 6, 3, 9],
       [1, 9, 4, 2],
       [5, 6, 2, 5],
       [7, 7, 2, 2]])

In [27]:
np.exp(arr)

array([[1.48413159e+02, 4.03428793e+02, 2.00855369e+01, 8.10308393e+03],
       [2.71828183e+00, 8.10308393e+03, 5.45981500e+01, 7.38905610e+00],
       [1.48413159e+02, 4.03428793e+02, 7.38905610e+00, 1.48413159e+02],
       [1.09663316e+03, 1.09663316e+03, 7.38905610e+00, 7.38905610e+00]])

In [28]:
np.power(arr,2)

array([[25, 36,  9, 81],
       [ 1, 81, 16,  4],
       [25, 36,  4, 25],
       [49, 49,  4,  4]], dtype=int32)

In [29]:
np.median(arr)

5.0

In [30]:
np.std(arr)

2.4677608777999542