In [1]:
import numpy as np

In [2]:
l = [1,2,3,455,44]

In [22]:
arr = np.array(l)
arr

array([  1,   2,   3, 455,  44])

In [8]:
type(arr)

numpy.ndarray

In [15]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [16]:
arr1.ndim

2

In [17]:
arr.ndim

1

In [20]:
mat = np.matrix(l)

In [21]:
np.array(mat)

array([[  1,   2,   3, 455,  44]])

In [23]:
a  = arr

In [24]:
arr[0] = 100

In [25]:
arr

array([100,   2,   3, 455,  44])

In [26]:
a

array([100,   2,   3, 455,  44])

In [27]:
b = np.copy(arr)

In [28]:
b

array([100,   2,   3, 455,  44])

In [29]:
arr[0] = 123

In [30]:
arr

array([123,   2,   3, 455,  44])

In [31]:
b

array([100,   2,   3, 455,  44])

In [35]:
b [0] = 1234

In [36]:
b

array([1234,    2,    3,  455,   44])

In [37]:
arr

array([123,   2,   3, 455,  44])

In [38]:
# concept of deep copy and solo copy 

In [39]:
#function to create array 


In [40]:
np.fromfunction(lambda i,j : i ==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [41]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [44]:
list(i *i for i in range(5))

[0, 1, 4, 9, 16]

In [45]:
iterable = (i*i for i in range(5))

In [47]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [49]:
np.fromstring('23 45 56', sep =' ')

array([23., 45., 56.])

In [50]:
arr.ndim

1

In [51]:
arr.size

5